/**
 * ShipScore fix agent — GitHub PR builder (Day 3-4 skeleton).
 *
 * buildPullRequestSpec folds plan edits into commit payloads (pure).
 * openPullRequest performs the real GitHub REST dance — ONLY called when
 * the run is explicitly applied (GITHUB_TOKEN + FIX_AGENT_ENABLED=1 +
 * apply:true). Otherwise simulatePr returns the exact spec the agent
 * *would* push, which is what the demo shows.
 *
 * Token handling: read from env at call time, used only in Authorization
 * headers, never logged, never persisted, never returned.
 */

import { parseGithubUrl } from "@/lib/scanner/clone";
import type { FixPlan, PullRequestSpec } from "./types";
import { previewEdits } from "./apply";

const GITHUB_API = "https://api.github.com";
const BRANCH_PREFIX = "shipscore/fix";

/** human-readable PR body from the plans + report snapshot */
export function buildPrBody(plans: FixPlan[], meta: { repo: string; score: number; grade: string; engine: string }): string {
  const table = plans
    .map(
      (p) =>
        `| ${p.severity} | ${p.findingFile}:${p.findingLine} | ${p.title} | ${p.safe ? "mechanical" : "needs review"} |`,
    )
    .join("\n");

  return [
    `## ShipScore auto-fix — ${meta.repo}`,
    "",
    `Scanned at score **${meta.score}/100 (${meta.grade})** with \`${meta.engine}\`.`,
    "This PR applies the deterministic fixes below. Nothing here was written by an LLM — every edit comes from a reviewed rule in the ShipScore fix-agent.",
    "",
    `| Severity | Location | Fix | Risk |`,
    `|---|---|---|---|`,
    table,
    "",
    "_Generated by ShipScore fix-agent. Advisory findings (e.g. missing eval coverage) are tracked in the run notes, not patched blindly._",
  ].join("\n");
}

export interface BuildSpecInput {
  plans: FixPlan[];
  repoUrl: string;
  meta: { repo: string; score: number; grade: string; engine: string };
  /** read a file's current content from the scanned root (read-only) */
  readOriginal: (path: string) => string | null;
}

export interface BuiltSpec {
  spec: PullRequestSpec;
  warnings: string[];
  filesTouched: string[];
}

/** fold all plan edits into a full PR spec (branch, commits, body) */
export function buildPullRequestSpec(input: BuildSpecInput): BuiltSpec | { error: string } {
  const { plans, repoUrl, meta, readOriginal } = input;

  let ownerRepo: string;
  try {
    const { owner, repo } = parseGithubUrl(repoUrl);
    ownerRepo = `${owner}/${repo}`;
  } catch {
    return { error: "no github URL associated with this scan — PR authoring skipped" };
  }

  const patchable = plans.filter((p) => !p.advisory && p.edits.length > 0);
  if (patchable.length === 0) {
    return { error: "no mechanical fixes in this run — nothing to open a PR for" };
  }

  const { previews, warnings } = previewEdits(patchable, readOriginal);
  const safeEdits = patchable.filter((p) => p.safe);
  const reviewEdits = patchable.filter((p) => !p.safe);

  const spec: PullRequestSpec = {
    head: `${BRANCH_PREFIX}-${Date.now().toString(36)}`,
    base: "main",
    title:
      safeEdits.length > 0 && reviewEdits.length === 0
        ? `fix: ShipScore auto-fixes (${safeEdits.length} mechanical)`
        : `fix: ShipScore auto-fixes (${safeEdits.length} mechanical, ${reviewEdits.length} need review)`,
    body: buildPrBody(patchable, meta),
    commits: [
      {
        message: `fix: apply ${patchable.length} ShipScore fixes (score ${meta.score}/${meta.grade})`,
        files: previews.map((p) => ({ path: p.path, content: p.after, encoding: "utf-8" as const })),
      },
    ],
  };

  return {
    spec,
    warnings,
    filesTouched: previews.map((p) => p.path),
  };
}

/** no-network dry-run: return the spec unchanged with a clear reason */
export function simulatePr(spec: PullRequestSpec, reason: string): { simulated: true; spec: PullRequestSpec; reason: string } {
  return { simulated: true, spec, reason };
}

// --- real PR flow (gated) ----------------------------------------------------

function ghHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
    "User-Agent": "shipscore-fix-agent",
  };
}

async function gh<T>(token: string, pathUrl: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${GITHUB_API}${pathUrl}`, {
    ...init,
    headers: { ...ghHeaders(token), ...(init?.headers ?? {}) },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${res.status} on ${pathUrl}: ${text.slice(0, 200)}`);
  }
  return (await res.json()) as T;
}

/**
 * Open the PR for real. Requires a token. Sequence:
 * repo -> default branch sha -> create ref -> upsert files (contents API) -> open PR.
 */
export async function openPullRequest(spec: PullRequestSpec, repoUrl: string): Promise<{ url: string }> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set — refusing to touch GitHub");

  const { owner, repo } = parseGithubUrl(repoUrl);
  const root = `/repos/${owner}/${repo}`;

  const repoInfo = await gh<{ default_branch: string }>(token, root);
  const base = repoInfo.default_branch;

  const ref = await gh<{ object: { sha: string } }>(token, `${root}/git/ref/heads/${base}`);
  const baseSha = ref.object.sha;

  const branch = spec.head;
  await gh(token, `${root}/git/refs`, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  }).catch(async (e: Error) => {
    // branch may already exist from a previous run — verify instead of dying
    await gh(token, `${root}/git/ref/heads/${branch}`);
    if (!e.message.includes("422")) throw e;
  });

  for (const commit of spec.commits) {
    for (const file of commit.files) {
      let fileSha: string | undefined;
      try {
        const existing = await gh<{ sha: string }>(token, `${root}/contents/${encodeURIComponent(file.path)}?ref=${base}`);
        fileSha = existing.sha;
      } catch {
        /* new file — no sha */
      }
      await gh(token, `${root}/contents/${encodeURIComponent(file.path)}`, {
        method: "PUT",
        body: JSON.stringify({
          message: commit.message,
          content: Buffer.from(file.content, "utf-8").toString("base64"),
          branch,
          ...(fileSha ? { sha: fileSha } : {}),
        }),
      });
    }
  }

  const pr = await gh<{ html_url: string; number: number }>(token, `${root}/pulls`, {
    method: "POST",
    body: JSON.stringify({ title: spec.title, body: spec.body, head: branch, base }),
  });

  return { url: pr.html_url };
}
